### PR TITLE
csvclean: Use standard output and standard error, and use exit code 1 if errors

### LINKED ISSUE #195: csvclean: options for stdout and stderr
to output the fixed file on stdout and errors on stderr

### PR DESCRIPTION
**Pull request by jpmckinney**
Closes #195 

Not backwards compatible. Merge this after 1.0.2 so that 1.0.2 still gets bugfixes/improvements.

### CODE REVIEW

**Comment by mappingvermont** [comment]
👋 hi all! I ❤️ csvkit, and just wanted to bump this as it would be really helpful to use it to validate CSV files and return an exit code of 0/1. In the process.

Is this on the upcoming roadmap at all?

Thank you!

**Comment by jpmckinney** [comment]
@mappingvermont I'll try to have a look at this, but feel free to install this branch:

    pip install -e git+https://github.com/wireservice/csvkit.git@csvclean#egg=csvkit

**Comment by mappingvermont** [comment]
Awesome- thanks @jpmckinney. Currently getting around this with some 'fun' grep usage:

```bash
csv_valid_exit_code=$(csvclean "$csv_file" | grep 'errors logged' > /dev/null 2>&1; echo $?)
```

but just wanted to say +1 to having this as a general 'feature' in `csvclean`. Many thanks!

**Comment by kladiv** [comment]
+1 for exit code 1 if any error

**Comment by jpmckinney** [comment]
Redone in #1241

**Comment by mappingvermont** [comment]
Amazing! Thank you @jpmckinney! 🎉 🎉

**Pull request closed without merging**
