### PR TITLE
add Dockerfile and Makefile

### PR DESCRIPTION
**Pull request by briansorahan**

### CODE REVIEW

**Comment by jpmckinney** [comment]
@briansorahan Can you provide or link to some documentation on how to use these files, so that I can add that to csvkit's documentation?

**Comment by jpmckinney** [comment]
Also, why Python 2 and not Python 3?

**Comment by briansorahan** [comment]
re: 2 vs 3, what are your preferences @jpmckinney ?

As far as documentation, here is how I am using the image that results from the docker build:

I built and pushed to my docker hub acct by overriding the repo:

```
make clean image REPO=bsorahan
```

Then I setup shell functions to make the normal csvkit commands use docker:


```
csvcut()  { docker run --rm -i -v $(pwd):/root --entrypoint csvcut  -w /root bsorahan/csvkit "$@" }
csvlook() { docker run --rm -i -v $(pwd):/root --entrypoint csvlook -w /root bsorahan/csvkit "$@" }
in2csv()  { docker run --rm -i -v $(pwd):/root --entrypoint in2csv  -w /root bsorahan/csvkit "$@" }
```

In my case I added these lines to `.zshrc` ^^

This is a straightforward way for me to be able to use the csvkit tools without having to install/run pip on my laptop.

If you can give me some feedback on this usage pattern and point me to which file(s) I should edit to add docs, I can make that part of this PR

**Comment by jpmckinney** [comment]
My preference is 3, as it will be supported longer (no plans to drop 2 for a long time though!).

You can add this usage as a tip to this page of the docs: https://github.com/wireservice/csvkit/blob/master/docs/tricks.rst

Thanks!

**Comment by briansorahan** [comment]
@jpmckinney For the "docker run" commands do you prefer to push a `wireservice/csvkit` image to docker hub?
If so I think it would make sense to add 2 more steps to the `after_success` step [here](https://github.com/wireservice/csvkit/blob/master/.travis.yml):

```
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - make push
```

This would require someone to setup a docker hub account and [add](https://docs.travis-ci.com/user/docker/#Pushing-a-Docker-Image-to-a-Registry) the user/pass env variables in the "docker login" above to the travis repository settings.

wdyt?

This will influence the docs I add.

**Comment by jpmckinney** [comment]
Sounds good - I can create a docker hub account and add those variables.

**Comment by jpmckinney** [comment]
I created the hub account, but I need to be a repository admin to run `travis env set DOCKER_USERNAME` (getting "not allowed to access environment variables"). @onyxfish ?

**Comment by jpmckinney** [comment]
@briansorahan Is it possible to have a Dockerfile and Makefile task for each of Python 2.7 and 3.6?

**Comment by briansorahan** [comment]
Hey all I'm closing the PR because it's so old and I really don't have time to move it forward
I'll leave the branch in case anyone wants to pick this work back up

**Pull request closed without merging**
