### PR TITLE
csvsed: sed for tabular data

### PR DESCRIPTION
**Pull request by qauge**
What about adding a csvsed utility to csvkit?

I think the name speaks for itself. Here is a short example:
```
$ cat sample.csv \
  | csvsed -c Wage -m s/,//g \                                     # remove commas from the Wage column
  | csvsed -c Status -m 'y/A-Z/a-z/' \                           # convert Status to all lowercase
  | csvsed -c Status -m 's/.*(ok|good).*/\1/'                 # restrict to keywords 'ok' & 'good'
```

The code (GPL) is adapted from [https://github.com/metagriffin/csvsed](https://github.com/metagriffin/csvsed) with the authorization of its original author (metagriffin).

csvkit is amazing, by the way. I used it intensively during the last year. Thank you!

### CODE REVIEW

**Comment by qauge** [comment]
Unfortunately, the tests that don't pass on master either (at least on my machine).
I refer to #596

**Comment by jpmckinney** [comment]
Master is passing: https://travis-ci.org/wireservice/csvkit/builds/119057776

**Comment by jpmckinney** [comment]
Looks like error is in most recent version of agate.

**Comment by jpmckinney** [comment]
Thank you for preparing this new CSV tool. However, the maintainers have decided to not merge and maintain new tools; there is simply not enough time to maintain new tools. Our focus is instead on making the existing tools as good as possible.

We encourage you to release and maintain your tool as a separate Python package. You may want to use the agate library, which csvkit uses for most of its CSV reading and writing. Doing so will make it easier to maintain common behavior with csvkit’s tools.

**Comment by CMCDragonkai** [comment]
Damn I was hoping this would be available.

**Pull request closed without merging**
