### PR TITLE
if csvstack files have headers, union the headers and align data

### PR DESCRIPTION
**Pull request by fgregg**
This PR will address  #245. If the files input to csvstack have headers, then csvstack will create a header that is the union of those headers and align the data to those headers.

Todo

- [x] handle case where one of the input files is stdin
- [x] write tests for new functionality

### CODE REVIEW

**Comment by fgregg** [comment]
@jpmckinney , if you'd like to take an initial look and see if this approach is to your liking, that would be great. Feel free to wait until tests (and new test are written too).

**Comment by fgregg** [comment]
@jpmckinney, two years later. i think is is ready for your real review.

**Comment by jpmckinney** [comment]
Thank you! I added a commit but couldn't push to this branch, so I've opened #1193.

**Comment by jpmckinney** [comment]
1.1.1 is now released with this feature 🎉

**Pull request closed without merging**
