### PR TITLE
feat: make man pages be included in wheels too!

### LINKED ISSUE #1234: Include man pages in PyPI package tarballs?
Hi - would you be open to the man pages being included in the built barballs distributed to PyPI?

Followup from #15, #1104 

My ultimate goal is for the man pages to be accessible. I find myself regularly frustrated when using `csvkit` because I can't quickly lookup the man page for a command without clearing out my current shell pipeline to call `<tool> --help`. (My shell [has a keyboard shortcut](https://fishshell.com/docs/current/interactive.html#:~:text=Alt%2BH%20(or%20F1)%20shows%20the%20manual%20page%20for%20the%20current%20command%2C%20if%20one%20exists.) to pull up the man page for the command under cursor without clearing the command buffer.)

I do agree with your previous sentiment that the maintainers of this package cannot be responsible for making sure the man pages _end up_ in the right place. **However I think it _would_ be reasonable for this package to be responsible for _building_ its man pages.** Could this package's build script(s) _generate_ the man pages and include them in tarballs uploaded to PyPI? That would greatly simplify distribution maintainers' jobs from "`python -m venv .venv && .venv/bin/pip install docs/requirements.txt && PATH=.venv/bin:$PATH make -C docs man && cp docs/_build/man/* ...`" (which, to my knowledge, no one does currently because it's non-trivial) to simply "`cp docs/_build/man/* ...`" (which would be _very_ easy to add).

Would you be open to reviewing & merging a PR to this effect?

### PR DESCRIPTION
**Pull request by vergenzt**
#1235 only managed to get them included in sdists 🙈

Resolves #1234 for real now

I tested and confirmed now that _both_ sdists _and_ wheels end up with the files!

### CODE REVIEW

**Comment by jpmckinney** [comment]
Reading the Stackoverflow message, does MANIFEST.in need to be updated, or no?

**Comment by harkabeeparolus** [comment]
> Reading the Stackoverflow message, does MANIFEST.in need to be updated, or no?

No, MANIFEST.in rules are not needed for something explicitly specified with `data_files`:

> [...] More precisely, the following files are included in a source distribution by default:
> [...]
> * All files specified by the `package-data` and `data-files` configuration parameters in `pyproject.toml` and/or equivalent in `setup.cfg`/`setup.py`;

[Source: <https://setuptools.pypa.io/en/latest/userguide/miscellaneous.html>]

**Comment by harkabeeparolus** [comment]
By the way, is there anything I could do to help get this PR past the finish line? I use csvkit daily, and I'm also a Python dev.

**Comment by jpmckinney** [comment]
Aha, wheel ignores `include_package_data` and `MANIFEST.in`.

**Comment by harkabeeparolus** [comment]
Thanks! 🤩 🙏

**Comment by vergenzt** [comment]
Thanks so much you two!!

**Comment by vergenzt** [comment]
PR to link the man pages in Homebrew formula is here: https://github.com/Homebrew/homebrew-core/pull/192380

**Pull request merged**
