### PR TITLE
Change default CSV encoding to UTF-8 BOM

### PR DESCRIPTION
**Pull request by felixbuenemann**
Since Python's 'utf-8-sig' encoding works with and without BOM, we can support UTF-8 with BOM by changing the default encoding.

Resolves: #1007

### CODE REVIEW

**Comment by felixbuenemann** [comment]
@jpmckinney I noticed that there is a section about UTF-8 with BOM in [docs/tricks.rst](https://github.com/wireservice/csvkit/blob/master/docs/tricks.rst#reading-a-csv-with-a-byte-order-mark-bom).

Should I remove the section or change it to state that this is now the default behavior?

**Comment by jpmckinney** [comment]
I think we can just remove it. Thanks! Let me know when you've added the commit.

**Comment by felixbuenemann** [comment]
> I think we can just remove it. Thanks! Let me know when you've added the commit.

Done.

**Comment by jpmckinney** [comment]
Thanks!! I've added you to `AUTHORS`.

**Pull request merged**
