### PR TITLE
csvformat: Accept escaped characters as argument values

### PR DESCRIPTION
**Pull request by jpmckinney**

### CODE REVIEW

**Comment by jpmckinney** [comment]
Hmm. I can't find a way to do this yet with `six` or `codecs` in both Python versions.

**Comment by onyxfish** [comment]
This looks good, but I'm wondering why I've never run into this issue with the input delimiters...

**Comment by onyxfish** [comment]
Maybe there is something in argparse that can help with this?

**Comment by jpmckinney** [comment]
Actually, I'll fix with documentation.

**Pull request closed without merging**
